export * from "./cfg.service";
export * from "./clientes.service";
export * from "./pedidos.service";
export * from "./pedido-itens.service";
export * from "./produtos.service";
export * from "./pagamentos.service";
export * from "./equipe.service";
export * from "./metricas.service";
export * from "./tabela-precos.service";
