// Tipos de domínio Vendas — derivados via z.infer em src/lib/vendas/schemas.ts.
// Este arquivo é compat shim; novos imports devem vir de @/lib/vendas/schemas.

export type {
  AdicionarItemPayload,
  ChartSeries,
  ClienteBusca,
  ClienteDetalhe,
  ClienteFormPayload,
  ClienteInativo,
  ClienteRedeSP,
  CondicaoPagamento,
  Emitente,
  FecharPedidoPayload,
  FormaPagamento,
  ImpostoCalculado,
  ItemTabelaPrecos,
  MembroEquipe,
  MetricaChartResponse,
  NovoPedidoPayload,
  Operacao,
  PedidoCriado,
  PedidoDetalhe,
  PedidoItem,
  PedidoLista,
  ProdutoBusca,
  ProdutoPreco,
  TenantCfg,
  ViaCepData,
} from "@/lib/vendas/schemas";
